### ISSUE TITLE
Refactor to make properties declaration less insane!

### ISSUE THREAD

**Issue by kanitw** [vega/compassql#297]
- [ ] Extract the long methods on top of `model.ts`

- [ ] Think about ways that we can make new property declaration (e.g., in `property.ts` less insane)

**Comment by kanitw** [comment]
- [ ] `keyof` and lookup types can be useful https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#keyof-and-lookup-types

**Comment by domoritz** [comment]
I like less insane!

**Comment by kanitw** [comment]
We can further optimize this in TS 2.1 using `keyof`. 

Basically, 

- [ ] replace switch cases in `wildcard.ts`'s `getDefaultName` with a new dictionary `DEFAULT_NAME` in PROPERTY.TS.

```
/** Default names for all encoding property */
export DEFAULT_ENCODING_PROPERTY_NAME = {
   channel: 'c',
   ...
};

export const DEFAULT_NAME = {
   // list all other 
   mark: 'm',
   filter: 'f',
   // Using object spread 
   ...DEFAULT_ENCODING_PROPERTY_NAME
}
```
(and getDefaultName just return the dictionary's value) 

```
export function getDefaultName(prop: Property) {
  return DEFAULT_NAME[prop];
}
```

- [ ] then use`keyof` to declare `type PROPERTY`

```
export type PROPERTY = keyof typeof DEFAULT_NAME;
```

- [ ] use `util.keys` to declare `ENCODING_PROPERTIES` 
```
ENCODING_PROPERTIES = util.keys(DEFAULT_ENCODING_PROPERTY_NAME);
```

- [ ] Also remove `namespace Property` or a part of it.

**Comment by kanitw** [comment]
Done as a part of #310
