### ISSUE TITLE
Outdated description?

### ISSUE THREAD

**Issue by domoritz** [vega/compassql#340]
https://github.com/vega/compassql/blob/master/src/constraint/spec.ts#L256

**Comment by kanitw** [comment]
Which constraint are you referring to?  The line links to master, which is now out of sync with your comment already.

**Comment by domoritz** [comment]
<img width="1031" alt="screen shot 2017-03-14 at 21 30 39" src="https://cloud.githubusercontent.com/assets/589034/23929559/7e55946c-08fd-11e7-83f9-eceab38d5de9.png">
