### ISSUE TITLE
Setup infrastructure to compile examples query and maintain output

### ISSUE THREAD

**Issue by kanitw** [vega/compassql#410]
- [x] have a script to run all examples with `recommend` method
- [x] each item would either a SpecQueryModel_Group_ or SpecQueryModel
  - [x] For specQueryModel, map them to shorthand ( `specQMs.map(x => x.toShorthand()` ) 
  - use `isSpecQueryGroup` to check if it is a group

- [x] check if the compiler has changed in Travis: 
  - look at `npm run build:examples-only` and then `npm run check:examples` in `.travis.yml` in Vega-Lite

**Comment by kanitw** [comment]
@haldenl Is there any task left for this issue?

**Comment by haldenl** [comment]
Everything is done!
